// Generated by https://quicktype.io

// export interface CollectionsProps {
//   data: collections;
// }

export interface CollectionsProps {
  id: string;
  is_active: boolean;
  name: string;
  updated_at: string;
  created_at: string;
}

export type UpdateCollectionsProps = Omit<
  CollectionsProps,
  "updated_at" | "created_at"
>;

export type CreateCollectionsPayload = Pick<CollectionsProps, "name">;
